//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MxCADViewWrapper : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MxCADViewWrapper(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MxCADViewWrapper obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MxCADViewWrapper obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MxCADViewWrapper() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MxCADWrapperLibPINVOKE.delete_MxCADViewWrapper(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public MxCADViewWrapper() : this(MxCADWrapperLibPINVOKE.new_MxCADViewWrapper(), true) {
  }

  public bool Create(int width, int height, global::System.IntPtr hParentWnd, bool isVisible, int posx, int posy) {
    bool ret = MxCADWrapperLibPINVOKE.MxCADViewWrapper_Create__SWIG_0(swigCPtr, width, height, hParentWnd, isVisible, posx, posy);
    return ret;
  }

  public bool Create(int width, int height, global::System.IntPtr hParentWnd, bool isVisible, int posx) {
    bool ret = MxCADWrapperLibPINVOKE.MxCADViewWrapper_Create__SWIG_1(swigCPtr, width, height, hParentWnd, isVisible, posx);
    return ret;
  }

  public bool Create(int width, int height, global::System.IntPtr hParentWnd, bool isVisible) {
    bool ret = MxCADWrapperLibPINVOKE.MxCADViewWrapper_Create__SWIG_2(swigCPtr, width, height, hParentWnd, isVisible);
    return ret;
  }

  public bool Create(int width, int height, global::System.IntPtr hParentWnd) {
    bool ret = MxCADWrapperLibPINVOKE.MxCADViewWrapper_Create__SWIG_3(swigCPtr, width, height, hParentWnd);
    return ret;
  }

  public bool Free() {
    bool ret = MxCADWrapperLibPINVOKE.MxCADViewWrapper_Free(swigCPtr);
    return ret;
  }

  public bool ReadFile(string pszFileName) {
    bool ret = MxCADWrapperLibPINVOKE.MxCADViewWrapper_ReadFile(swigCPtr, pszFileName);
    return ret;
  }

  public void UpdateDisplay(bool isClearOpenGL) {
    MxCADWrapperLibPINVOKE.MxCADViewWrapper_UpdateDisplay__SWIG_0(swigCPtr, isClearOpenGL);
  }

  public void UpdateDisplay() {
    MxCADWrapperLibPINVOKE.MxCADViewWrapper_UpdateDisplay__SWIG_1(swigCPtr);
  }

  public bool SetMxDrawPosition(int posx, int posy, int width, int height) {
    bool ret = MxCADWrapperLibPINVOKE.MxCADViewWrapper_SetMxDrawPosition(swigCPtr, posx, posy, width, height);
    return ret;
  }

}
