/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mxcad.wrapper;

public class MxCADAppWrapper {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MxCADAppWrapper(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MxCADAppWrapper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MxCADAppWrapper obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MxCADWrapperJNI.delete_MxCADAppWrapper(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MxCADAppWrapper() {
    this(MxCADWrapperJNI.new_MxCADAppWrapper(), true);
  }

  public boolean Free() {
    return MxCADWrapperJNI.MxCADAppWrapper_Free(swigCPtr, this);
  }

}
