/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mxcad.wrapper;

public class MxCADObjectWrapper {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MxCADObjectWrapper(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MxCADObjectWrapper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MxCADObjectWrapper obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MxCADWrapperJNI.delete_MxCADObjectWrapper(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MxCADObjectWrapper() {
    this(MxCADWrapperJNI.new_MxCADObjectWrapper(), true);
  }

  public boolean Create() {
    return MxCADWrapperJNI.MxCADObjectWrapper_Create(swigCPtr, this);
  }

  public int ReadFile(String fileName) {
    return MxCADWrapperJNI.MxCADObjectWrapper_ReadFile(swigCPtr, this, fileName);
  }

  public int WriteFile(String fileName) {
    return MxCADWrapperJNI.MxCADObjectWrapper_WriteFile(swigCPtr, this, fileName);
  }

  public int DrawLine(double x1, double y1, double x2, double y2) {
    return MxCADWrapperJNI.MxCADObjectWrapper_DrawLine(swigCPtr, this, x1, y1, x2, y2);
  }

  public int DrawCircle(double x, double y, double r) {
    return MxCADWrapperJNI.MxCADObjectWrapper_DrawCircle(swigCPtr, this, x, y, r);
  }

}
