/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mxcad.wrapper;

public class MxCADWrapperJNI {
  public final static native long new_MxCADAppWrapper();
  public final static native void delete_MxCADAppWrapper(long jarg1);
  public final static native boolean MxCADAppWrapper_Free(long jarg1, MxCADAppWrapper jarg1_);
  public final static native long new_MxCADObjectWrapper();
  public final static native void delete_MxCADObjectWrapper(long jarg1);
  public final static native boolean MxCADObjectWrapper_Create(long jarg1, MxCADObjectWrapper jarg1_);
  public final static native int MxCADObjectWrapper_ReadFile(long jarg1, MxCADObjectWrapper jarg1_, String jarg2);
  public final static native int MxCADObjectWrapper_WriteFile(long jarg1, MxCADObjectWrapper jarg1_, String jarg2);
  public final static native int MxCADObjectWrapper_DrawLine(long jarg1, MxCADObjectWrapper jarg1_, double jarg2, double jarg3, double jarg4, double jarg5);
  public final static native int MxCADObjectWrapper_DrawCircle(long jarg1, MxCADObjectWrapper jarg1_, double jarg2, double jarg3, double jarg4);
}
